openapi: 3.0.0
info:
  title: Purchase API
  description: API for listing purchases
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: Lab server
paths:
  /api/purchases:
    get:
      summary: Returns a list of purchases
      responses:
        '200':
          description: A JSON array of purchases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Purchase'
components:
  schemas:
    Purchase:
      type: object
      required:
        - id
        - name
        - amountDollars
        - purchaseType
        - date
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          minLength: 1
          maxLength: 50
          pattern: "[a-zA-Z0-9\ -]+"
        purchaseType:
          $ref: '#/components/schemas/PurchaseType'
        amountDollars:
          type: number
          format: double
        date:
          type: string
          format: date
    PurchaseType:
      type: string
      enum:
        - Book
        - Tool
        - Ps4
        - Switch
        - Steam
        - Collection
        - Sport